apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 30s
  path: ./gitops/flux/runtime/source/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-proxy-injector
      namespace: linkerd
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-identity
      namespace: linkerd
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-controller
      namespace: linkerd
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-sp-validator
      namespace: linkerd
    - apiVersion: apps/v1
      kind: Deployment
      name: linkerd-destination
      namespace: linkerd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-viz
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd
  interval: 30s
  path: ./gitops/flux/runtime/source/linkerd-viz
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tap
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: metrics-api
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: grafana
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: tap-injector
      namespace: linkerd-viz
    - apiVersion: apps/v1
      kind: Deployment
      name: web
      namespace: linkerd-viz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd-viz
  interval: 30s
  path: ./gitops/flux/runtime/source/flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: linkerd-viz